/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zachsRSHelper;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author zech
 */
public class GUIFrame extends javax.swing.JFrame {

    /**
     * Class level variables
     */
    private boolean inventoryDropperIsConfigured = false;
    //private InventoryConfigPanel invConfigPanel = new InventoryConfigPanel();
    /**
     * Creates new form GUIFrame
     */
    public GUIFrame() {
        initComponents();
        inventoryConfigPanel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        invConfigButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        invRunButton = new javax.swing.JButton();
        inventoryConfigPanel1 = new zachsRSHelper.InventoryConfigPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Zachs RS Helper");

        invConfigButton.setText("Configure");
        invConfigButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invConfigButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Inventory Dropper:");

        invRunButton.setText("Run");
        invRunButton.setEnabled(false);

        inventoryConfigPanel1.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(invRunButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(invConfigButton))
                    .addComponent(inventoryConfigPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invConfigButton)
                    .addComponent(jLabel3)
                    .addComponent(invRunButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addComponent(inventoryConfigPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void invConfigButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invConfigButtonActionPerformed
        // TODO add your handling code here:
        //invConfigPanel.setVisible(true);
        inventoryConfigPanel1.setVisible(true);
        inventoryConfigPanel1.setEnabled(true);
    }//GEN-LAST:event_invConfigButtonActionPerformed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
        /*if(inventoryConfigPanel1.isSetting){
            Point b = MouseInfo.getPointerInfo().getLocation();
            int x = (int) b.getX();
            int y = (int) b.getY();
            System.out.printf("click jframe x:%d y:%d\n",x,y);
            
            //JFrame jimmy = new JFrame();
            //jimmy.setUndecorated(true);
           // jimmy.getContentPane().setBackground(new Color(1.0f,1.0f,1.0f,0.0f));
            //jimmy.setBackground(new Color(1.0f,1.0f,1.0f,0.0f));

            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            double width = screenSize.getWidth();
            double height = screenSize.getHeight();
            //System.out.printf("width:%f Height:%f\n",width,height);
            //jimmy.setBounds(x-100,y-100,400,400);
            //JLabel label1 = new JLabel("Select one corner to another of RS");
            //label1.setBackground(Color.white);
            //label1.setFont(new Font("Dialog",Font.BOLD,22));
            //jimmy.add(label1);
            //jimmy.setVisible(true);
        }
        */
    }//GEN-LAST:event_formWindowLostFocus

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        if(inventoryConfigPanel1.isSetting){
            inventoryConfigPanel1.isSetting = false;
            System.out.println("GUIFrame gained focus after setting");
            int x1 = inventoryConfigPanel1.data[0];
            int y1 = inventoryConfigPanel1.data[1];
            int x2 = inventoryConfigPanel1.data[2];
            int y2 = inventoryConfigPanel1.data[3];
            System.out.printf("GUIFrame x1:%d y1:%d x2:%d y2:%d \n",x1,y1,x2,y2);
            inventoryConfigPanel1.enableCheck();
        }
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton invConfigButton;
    private javax.swing.JButton invRunButton;
    private zachsRSHelper.InventoryConfigPanel inventoryConfigPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
